-- Inserts to Locations table
INSERT INTO [Locations] (Name, Latitude, Longitude, Active, Description)
VALUES
('Auditorio Juan Lindo', 14.084703, -87.162745, 1, 'Frente al Rótulo -Auditorium'),
('Registro UNAH', 14.084073, -87.163047, 1, 'Frente al Rótulo -Registro'),
('Biblioteca UNAH', 14.08555, -87.16324, 1, 'Frente a la entrada principal de la Librería'),
('Edificio F1', 14.08488, -87.164226, 1, 'Salida que va hacia la calle Hollywood, primer piso'),
('Edificio D1', 14.08564, -87.16401, 1, 'Salida que va hacia la calle Hollywood, primer piso'),
('Edificio 1847', 14.08513, -87.16508, 1, 'Entrada pricipal, frente al Comedor Universitario'),
('Edificio J1', 14.08616, -87.16656, 1, 'Frente a la entrada a la Clínica Universitaria'),
('Edificio G1', 14.08376, -87.1657, 1, 'Justo frente a la entrada principal del edificio'),
('Edificio I1', 14.08413, -87.16757, 1, 'Justo frente a la entrada principal del edificio'),
('Edificio H1', 14.08386, -87.16656, 1, 'Justo frente a la entrada principal del edificio'),
('Edificio Alma Máter', 14.08393, -87.16183, 1, 'Frente a la entrada principal del Edificio Administrativo'),
('Edificio A2', 14.0857, -87.16214, 1, 'Justo frente a la entrada principal del edificio'),
('Edificio B1', 14.08612, -87.16171, 1, 'En la entrada principal del edificio'),
('Edificio B2', 14.08668, -87.16198, 1, 'En la entrada principal del edificio'),
('Edificio A1', 14.085004, -87.16212, 1, 'Justo en la entrada principal del edificio'),
('CRA-DEGT UNAH', 14.0851, -87.16276, 1, 'Frente a la entrada del CRA'),
('Edificio E1', 14.08388, -87.16238, 1, 'Justo en la entrada principal al edificio'),
('CISE', 14.0848, -87.16565, 1, 'Frente al cajero de Banco Atlántida (ATM)'),
('Escuela UNAH', 14.08683, -87.16762, 1, 'Entrada principal a la Escuela Experimental de la UNAH'),
('Polideportivo', 14.08512, -87.17096, 1, 'Entrada principal al Palacio Universitario de los Deportes'),
('Observatorio', 14.08742, -87.15945, 1, 'Frente al Observatorio Astronómico Centroamericano'),
('Reloj', 14.08492, -87.16496, 1, 'Frente al Reloj Solar');

INSERT INTO [Careers] (Name, Active)
VALUES
('Ingeniería en Sistemas', TRUE),
('Medicina', TRUE),
('Derecho', TRUE),
('Administración de Empresas', TRUE),
('Contaduría Pública', TRUE),
('Periodismo', TRUE),
('Lenguas Extranjeras', TRUE),
('Psicología', TRUE),
('Pedagogía', TRUE),
('Trabajo Social', TRUE),
('Historia', TRUE),
('Letras', TRUE),
('Filosofía', TRUE),
('Sociología', TRUE),
('Educación Física', TRUE),
('Lenguas Extranjeras con Orientación en Inglés y Francés', TRUE),
('Música', TRUE),
('Desarrollo Local', TRUE),
('Ingeniería Civil', TRUE),
('Ingeniería Mecánica Industrial', TRUE),
('Ingeniería Eléctrica Industrial', TRUE),
('Ingeniería Industrial', TRUE),
('Arquitectura', TRUE),
('Comunicación Audiovisual', TRUE),
('Matemática Pura', TRUE),
('Matemáticas Aplicadas', TRUE),
('Física', TRUE),
('Astronomía y Astrofísica', TRUE),
('Odontología', TRUE),
('Nutrición', TRUE),
('Química y Farmacia', TRUE),
('Enfermería', TRUE),
('Microbiología', TRUE),
('Biología', TRUE),
('Fonoaudiología', TRUE),
('Economía', TRUE),
('Contaduría Pública y Finanzas', TRUE),
('Administración Aduanera', TRUE),
('Administración de Banca y Finanzas', TRUE),
('Comercio Internacional', TRUE),
('Informática Administrativa', TRUE),
('Relaciones Internacionales', TRUE),
('Analítica de Datos', TRUE),
('Ingeniería en Protección y Seguridad Privada', TRUE),
('Maquinaria Pesada', TRUE),
('Carreras Agropecuarias', TRUE),
('Biosociología', TRUE),
('Hidrología', TRUE);
