name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: self-hosted  # Usar runner self-hosted

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag Docker image
      run: |
        # Obtener el nombre del repositorio dinámicamente
        $repo = "${{ github.repository }}".ToLower()

        # Construir el nombre de la imagen
        $imageName = "ghcr.io/$repo/api:dev"
        echo "Building $imageName"
        
        # Construir la imagen Docker
        docker build --no-cache -t $imageName -f Backend/API/Dockerfile Backend

    - name: Debug output - check imageName
      run: |
        echo "Image Name: $imageName"  # Esto nos ayudará a ver el valor de imageName

    - name: Push Docker image to GitHub Container Registry
      run: |
        # Asegurarse de que imageName no esté vacío
        echo "Pushing image $imageName"
        docker push $imageName
