name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: self-hosted  # Usar runner self-hosted

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag Docker image
      id: build_image
      run: |
        # Obtener el nombre del repositorio dinámicamente
        repo="${{ github.repository }}".ToLower()
        
        # Construir el nombre de la imagen
        imageName="ghcr.io/$repo/api:dev"
        
        # Exportar la variable de imagen para uso posterior
        echo "IMAGE_NAME=$imageName" >> $GITHUB_ENV
        
        echo "Building $imageName"
        
        # Construir la imagen Docker
        docker build --no-cache -t $imageName -f Backend/API/Dockerfile Backend

    - name: Debug output - check imageName
      run: |
        echo "Image Name from env: ${{ env.IMAGE_NAME }}"  # Esto nos ayudará a ver el valor de imageName exportado

    - name: Push Docker image to GitHub Container Registry
      run: |
        # Asegurarse de que IMAGE_NAME no esté vacío
        echo "Pushing image ${{ env.IMAGE_NAME }}"
        docker push ${{ env.IMAGE_NAME }}
