# Crea la imagen de docker al recibir un PR

name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: self-hosted  # Usar runner self-hosted

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag Docker image
      run: |
        # Obtener el nombre del repositorio dinámicamente
        REPO_NAME="${{ github.repository }}"
        REPO_LOWER=$(echo "$REPO_NAME" | awk '{print tolower($0)}')
        
        # Construir el nombre de la imagen
        IMAGE_NAME="ghcr.io/${REPO_LOWER}/api:dev"
        echo "Building $IMAGE_NAME"
        
        # Construir la imagen Docker
        docker build --no-cache -t $IMAGE_NAME -f Backend/API/Dockerfile Backend

    - name: Push Docker image to GitHub Container Registry
      run: |
        # Empujar la imagen Docker al registro de GitHub
        docker push $IMAGE_NAME
